version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: IntelliTrader-DB
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - IntelliTrader_data:/var/lib/postgresql/data

volumes:
  IntelliTrader_data: 