version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: IntelliTrader-DB
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - IntelliTrader_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: IntelliTrader-MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - IntelliTrader_mysql_data:/var/lib/mysql

volumes:
  IntelliTrader_data: 
  IntelliTrader_mysql_data: 