name: release-please

on:
  push:
    branches:
      - release
    paths-ignore:
      - 'CHANGELOG.md'
      - '.release-please-manifest.json'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: release

      - name: Log Release Details
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "Major: ${{ steps.release.outputs.major }}"
          echo "Minor: ${{ steps.release.outputs.minor }}"
          echo "Patch: ${{ steps.release.outputs.patch }}"