name: release-please

on:
  pull_request:
    types: [closed]
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    # Improved condition to check PR author and title pattern
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'github-actions[bot]' &&
      !contains(github.event.pull_request.title, 'chore: release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-release: false
          clean: true
          
      - name: Show Release Output
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "::group::Release Information"
          echo "Tag Name: ${TAG_NAME}"
          echo "Release SHA: ${RELEASE_SHA}"
          echo "Release PR: ${PR_NUMBER}"
          echo "Version: ${MAJOR}.${MINOR}.${PATCH}"
          echo "::endgroup::"
        env:
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
          RELEASE_SHA: ${{ steps.release.outputs.sha }}
          PR_NUMBER: ${{ steps.release.outputs.pr }}
          MAJOR: ${{ steps.release.outputs.major }}
          MINOR: ${{ steps.release.outputs.minor }}
          PATCH: ${{ steps.release.outputs.patch }}