name: release-please

on:
  push:
    branches:
      - release
    
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
