name: release-please

on:
  push:
    branches:
      - release
    
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        id: release
        if: ${{ !contains(github.event.head_commit.message, 'chore: release') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: intellitrader
          bump-minor-pre-major: true

      - name: Show Release Output
        if: ${{ steps.release.outputs.release_created && !contains(github.event.head_commit.message, 'chore: release') }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Release SHA: ${{ steps.release.outputs.sha }}"

      - name: Create Release
        if: ${{ steps.release.outputs.release_created }}
        needs: [release]
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: Release ${{ steps.release.outputs.tag_name }}
          body: ${{ steps.release.outputs.body }}
          draft: false
          prerelease: false
