name: Auto Release

on:
  push:
    branches:
      - release  # or the default branch of your repository

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: "simple"  # Change this to match your project type (e.g., "python", "java", "ruby", etc.)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.release.outputs.release_created == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: ${{ steps.release.outputs.release_name }}
          body: ${{ steps.release.outputs.release_body }}
          draft: false
          prerelease: false