name: release-please

on:
  pull_request_target:
    types: [closed]
    branches:
      - release
    
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: googleapis/release-please-action@v4
        id: release
        if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'chore: release') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: intellitrader
          
      - name: Show Release Output
        if: ${{ steps.release.outputs.release_created && github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'chore: release') }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Release SHA: ${{ steps.release.outputs.sha }}"
          
      - name: Create Release
        if: ${{ steps.release.outputs.release_created && github.event.pull_request.merged == true }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: Release ${{ steps.release.outputs.tag_name }}
          body: ${{ steps.release.outputs.body }}
          draft: false
          prerelease: false
