name: release-please

on:
  pull_request:
    types: [closed]
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'github-actions[bot]' &&
      !contains(github.event.pull_request.title, 'chore: release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          release-type: simple
          
      - name: Delete existing tag if exists
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        run: |
          echo "Checking for existing tag: $TAG_NAME"
          if gh release view "$TAG_NAME" &>/dev/null; then
            echo "Deleting existing release and tag: $TAG_NAME"
            gh release delete "$TAG_NAME" --yes
            git push --delete origin "$TAG_NAME" || true
          fi
          
      - name: Create GitHub Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
          SHA: ${{ steps.release.outputs.sha }}
        run: |
          echo "Creating release for tag: $TAG_NAME"
          gh release create "$TAG_NAME" \
            --target $SHA \
            --title "Release $TAG_NAME" \
            --notes "$(cat CHANGELOG.md)" \
            --latest
          
      - name: Show Release Output
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "::group::Release Information"
          echo "Tag Name: ${{ steps.release.outputs.tag_name }}"
          echo "Release SHA: ${{ steps.release.outputs.sha }}"
          echo "Release PR: ${{ steps.release.outputs.pr }}"
          echo "Version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          echo "::endgroup::"