name: release-please

on:
  pull_request:
    types: [closed]
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'github-actions[bot]' &&
      !contains(github.event.pull_request.title, 'chore: release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          release-type: simple
          default-branch: release

  notify:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Notification Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
          VERSION: ${{ needs.release-please.outputs.version }}
        run: |
          gh issue create \
            --title "🎉 New Release: $TAG_NAME" \
            --body "A new version $VERSION has been released!

          ### What's Changed
          Please check the [release notes](https://github.com/${{ github.repository }}/releases/tag/$TAG_NAME) for details.

          ### Next Steps
          - [ ] Update documentation if needed
          - [ ] Monitor for any post-release issues
          - [ ] Update dependencies in dependent projects
          
          [View Release](${{ github.server_url }}/${{ github.repository }}/releases/tag/$TAG_NAME)" \
            --label "release" \
            --label "documentation"